# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeIntercomTester' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeIntercomTester

  pod 'Intercom'
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

end
